import type { ComposedGameSpec } from "./composed";
import { validateComposedGameSpec } from "./composed";

export const cinemaCharadesSpec: ComposedGameSpec = {
  schemaVersion: 2,
  id: "cinema_charades",
  template: "composed",
  title: "Cinéma sans paroles",
  description: "Deux équipes font deviner des films en les mimant, avec une nouvelle carte et un temps limité à chaque manche.",
  theme: "disco",
  minPlayers: 2,
  maxPlayers: 12,
  suggestedDurationMinutes: 20,
  setup: {
    mode: "teams",
    teamPolicy: {
      teams: [
        { id: "projecteurs", name: "Les Projecteurs", color: "#6c42f5" },
        { id: "clapboards", name: "Les Clapboards", color: "#ff6b4a" },
      ],
      minMembersPerTeam: 1,
      maxMembersPerTeam: 6,
      allocation: "balanced",
      allowUnevenTeams: true,
      rotateActivePlayer: true,
    },
    rounds: 6,
    startingPhaseId: "draw",
    startingPlayer: "random",
  },
  variables: [],
  choices: [],
  clues: [],
  reveals: [],
  orderingItems: [],
  matchingItems: [],
  boards: [],
  resources: [],
  randomizers: [],
  media: [],
  decks: [
    {
      id: "films",
      name: "Films à mimer",
      visibility: "private",
      shuffle: true,
      initialHandSize: 0,
      cards: [
        { id: "back_future", title: "Retour vers le futur", body: "Une voiture, une horloge et un voyage dans le temps.", icon: "🚗", tags: ["science_fiction"] },
        { id: "lion_king", title: "Le Roi Lion", body: "Un jeune lion doit reprendre sa place sur le trône.", icon: "🦁", tags: ["animation"] },
        { id: "titanic", title: "Titanic", body: "Une histoire d'amour sur un paquebot condamné.", icon: "🚢", tags: ["drame"] },
        { id: "matrix", title: "Matrix", body: "Un héros découvre que son monde est une simulation.", icon: "💊", tags: ["science_fiction"] },
        { id: "jaws", title: "Les Dents de la mer", body: "Un requin terrorise une station balnéaire.", icon: "🦈", tags: ["suspense"] },
        { id: "ghostbusters", title: "SOS Fantômes", body: "Une équipe capture des fantômes dans une grande ville.", icon: "👻", tags: ["comedie"] },
        { id: "rocky", title: "Rocky", body: "Un boxeur outsider prépare le combat de sa vie.", icon: "🥊", tags: ["sport"] },
        { id: "jurassic_park", title: "Jurassic Park", body: "Des dinosaures s'échappent dans un parc à thème.", icon: "🦖", tags: ["aventure"] },
        { id: "home_alone", title: "Maman, j'ai raté l'avion", body: "Un enfant défend sa maison contre deux cambrioleurs.", icon: "🏠", tags: ["comedie"] },
        { id: "harry_potter", title: "Harry Potter", body: "Un jeune sorcier découvre une école de magie.", icon: "🪄", tags: ["fantasy"] },
        { id: "finding_nemo", title: "Le Monde de Nemo", body: "Un poisson traverse l'océan pour retrouver son fils.", icon: "🐠", tags: ["animation"] },
        { id: "mission_impossible", title: "Mission Impossible", body: "Un agent secret réalise une mission extrêmement risquée.", icon: "🕵️", tags: ["action"] },
      ],
    },
  ],
  components: [
    { id: "game_header", kind: "header", audience: "public", eyebrow: "Jeu de mime", title: { kind: "literal", value: "Cinéma sans paroles" }, description: { kind: "literal", value: "Faites reconnaître le film avant la fin du chrono." }, icon: "🎬" },
    { id: "film_deck", kind: "deck", audience: "active_player", deckId: "films", label: "Film secret" },
    { id: "film_prompt", kind: "prompt", audience: "active_player", category: "Film à mimer", prompt: { kind: "active_card", deckId: "films", field: "title" }, hint: { kind: "active_card", deckId: "films", field: "body" }, icon: "🎭" },
    { id: "mime_timer", kind: "timer", audience: "public", seconds: 60, label: "Temps pour deviner" },
    { id: "turn", kind: "turn", audience: "public" },
    { id: "round", kind: "round", audience: "public", label: "Film" },
    { id: "teams", kind: "teams", audience: "public" },
    { id: "scores", kind: "scores", audience: "public", title: "Score des équipes" },
    { id: "outcome", kind: "outcome", audience: "public", title: { kind: "literal", value: "Fin de la séance !" }, description: { kind: "literal", value: "L'équipe ayant le plus de points remporte la partie." } },
  ],
  actions: [
    { id: "draw_film", label: "Piocher un film", kind: "draw", actor: "active_player", oncePerPhase: true, deckId: "films", effects: [{ kind: "draw_cards", deckId: "films", count: 1, target: "actor" }, { kind: "advance_phase" }] },
    { id: "film_guessed", label: "Film trouvé", kind: "complete_challenge", actor: "active_player", oncePerPhase: true, effects: [{ kind: "add_score", target: "actor_team", amount: 2 }, { kind: "discard_selected_card", deckId: "films", target: "actor" }, { kind: "advance_round", resetPhaseActions: true }, { kind: "set_active_player", mode: "next" }, { kind: "advance_phase" }] },
    { id: "film_passed", label: "Passer", kind: "advance", actor: "active_player", oncePerPhase: true, effects: [{ kind: "discard_selected_card", deckId: "films", target: "actor" }, { kind: "advance_round", resetPhaseActions: true }, { kind: "set_active_player", mode: "next" }, { kind: "advance_phase" }] },
  ],
  rules: [
    { id: "end_after_success", trigger: { kind: "after_action", actionId: "film_guessed" }, conditionMode: "all", conditions: [{ kind: "round_at_least", round: 7 }], effects: [{ kind: "end_game", winnerBy: "highest_score" }] },
    { id: "end_after_pass", trigger: { kind: "after_action", actionId: "film_passed" }, conditionMode: "all", conditions: [{ kind: "round_at_least", round: 7 }], effects: [{ kind: "end_game", winnerBy: "highest_score" }] },
  ],
  phases: [
    { id: "draw", title: "Découverte du film", componentIds: ["game_header", "round", "turn", "teams", "scores", "film_deck"], actionIds: ["draw_film"], nextPhaseId: "mime", completionMode: "manual", completionConditions: [], onComplete: [] },
    { id: "mime", title: "Mime en cours", componentIds: ["game_header", "round", "turn", "teams", "scores", "mime_timer", "film_prompt"], actionIds: ["film_guessed", "film_passed"], nextPhaseId: "draw", completionMode: "manual", completionConditions: [], onComplete: [] },
  ],
};

export const systemsLabSpec: ComposedGameSpec = {
  schemaVersion: 2,
  id: "systems_lab",
  template: "composed",
  title: "Laboratoire des mécaniques",
  description: "Une fixture jouable qui exerce chaque contrôle humain autorisé par le compilateur BoardForge.",
  theme: "laboratory",
  minPlayers: 2,
  maxPlayers: 2,
  suggestedDurationMinutes: 8,
  setup: { mode: "individual", rounds: 1, startingPhaseId: "play", startingPlayer: "first" },
  variables: [],
  choices: [{ id: "answer_a", label: "Réponse A", correct: true }, { id: "answer_b", label: "Réponse B", correct: false }],
  clues: [{ id: "clue_one", text: "Le premier indice a été révélé." }],
  reveals: [{ id: "secret_panel", title: "Révélation validée", description: "Le moteur a ouvert ce panneau sans exposer de donnée avant l’action.", icon: "✦" }],
  orderingItems: [{ id: "early", label: "Avant", rank: 1 }, { id: "middle", label: "Milieu", rank: 2 }, { id: "late", label: "Après", rank: 3 }],
  matchingItems: [{ id: "cat", label: "Chat", pairId: "animals" }, { id: "dog", label: "Chien", pairId: "animals" }, { id: "red", label: "Rouge", pairId: "colors" }, { id: "blue", label: "Bleu", pairId: "colors" }],
  decks: [{
    id: "tools", name: "Outils", visibility: "private", shuffle: false, initialHandSize: 1,
    cards: [
      { id: "hammer", title: "Marteau", body: "Un outil robuste.", icon: "🔨", tags: [] },
      { id: "rope", title: "Corde", body: "Un outil souple.", icon: "🪢", tags: [] },
      { id: "lamp", title: "Lampe", body: "Éclaire la suite.", icon: "🔦", tags: [] },
      { id: "compass", title: "Boussole", body: "Indique la direction.", icon: "🧭", tags: [] },
    ],
  }],
  boards: [{ id: "track", name: "Piste d’essai", layout: "track", spaces: [{ id: "start", label: "Départ" }, { id: "middle_space", label: "Étape" }, { id: "finish", label: "Arrivée" }], tokens: [{ id: "pawn", label: "Pion", owner: "player", startSpaceId: "start" }] }],
  resources: [{ id: "energy", name: "Énergie", icon: "⚡", scope: "player", initialValue: 1, min: 0, max: 5 }],
  randomizers: [
    { id: "die", kind: "die", label: "Dé de test", sides: 6 },
    { id: "spinner", kind: "spinner", label: "Roue de test", options: [{ id: "north", label: "Nord" }, { id: "south", label: "Sud" }] },
  ],
  media: [{ id: "lab_visual", kind: "image", title: "Visuel distant sécurisé", url: "https://example.com/boardforge-lab.png", alt: "Emplacement de média de démonstration" }],
  components: [
    { id: "header", kind: "header", audience: "public", eyebrow: "Fixture de validation", title: { kind: "literal", value: "Laboratoire des mécaniques" }, description: { kind: "literal", value: "Tous les contrôles ci-dessous sont reliés au moteur déterministe." }, icon: "🧪" },
    { id: "prompt", kind: "prompt", audience: "public", category: "Mission", prompt: { kind: "literal", value: "Essayez chaque interaction puis terminez la partie." } },
    { id: "choices", kind: "choices", audience: "public", title: "Choix structuré", optionIds: ["answer_a", "answer_b"], columns: 2 },
    { id: "text", kind: "text_input", audience: "public", label: "Réponse libre", placeholder: "Écrivez un court message", multiline: false, maxLength: 180 },
    { id: "drawing", kind: "drawing", audience: "public", label: "Ardoise locale" },
    { id: "players", kind: "players", audience: "public" },
    { id: "clues", kind: "clues", audience: "public", title: "Indices", clueIds: ["clue_one"] },
    { id: "challenge", kind: "challenge", audience: "public", title: { kind: "literal", value: "Défi tactile" }, instruction: { kind: "literal", value: "Validez ce défi depuis les actions disponibles." }, difficulty: "easy", rewardLabel: "+1 test", icon: "⚡" },
    { id: "reveal", kind: "reveal", audience: "public", revealId: "secret_panel" },
    { id: "board", kind: "board", audience: "public", boardId: "track" },
    { id: "deck", kind: "deck", audience: "public", deckId: "tools", label: "Pioche d’outils" },
    { id: "hand", kind: "card_zone", audience: "public", deckId: "tools", zone: "hand" },
    { id: "resources", kind: "resources", audience: "public", resourceIds: ["energy"] },
    { id: "die", kind: "randomizer", audience: "public", randomizerId: "die" },
    { id: "spinner", kind: "randomizer", audience: "public", randomizerId: "spinner" },
    { id: "buzz", kind: "buzzer", audience: "public", label: "Buzzer de test" },
    { id: "order", kind: "ordering", audience: "public", itemIds: ["early", "middle", "late"] },
    { id: "match", kind: "matching", audience: "public", itemIds: ["cat", "dog", "red", "blue"] },
    { id: "media", kind: "media", audience: "public", mediaId: "lab_visual" },
    { id: "outcome", kind: "outcome", audience: "public", title: { kind: "literal", value: "Fixture terminée" }, description: { kind: "literal", value: "Chaque mécanique a disposé d’un contrôle humain." } },
  ],
  actions: [
    { id: "move", label: "Déplacer le pion", kind: "move", actor: "active_player", oncePerPhase: true, boardId: "track", effects: [{ kind: "move_selected_token", boardId: "track" }] },
    { id: "energize", label: "Gagner de l’énergie", kind: "resource", actor: "active_player", oncePerPhase: true, effects: [{ kind: "add_resource", resourceId: "energy", target: "actor", amount: 2 }] },
    { id: "roll", label: "Lancer le dé", kind: "randomize", actor: "active_player", oncePerPhase: true, randomizerId: "die", effects: [{ kind: "randomize", randomizerId: "die" }] },
    { id: "spin", label: "Tourner la roue", kind: "randomize", actor: "active_player", oncePerPhase: true, randomizerId: "spinner", effects: [{ kind: "randomize", randomizerId: "spinner" }] },
    { id: "buzz", label: "Buzzer", kind: "buzz", actor: "any_player", oncePerPhase: true, effects: [] },
    { id: "order", label: "Valider l’ordre", kind: "order", actor: "active_player", oncePerPhase: true, itemIds: ["early", "middle", "late"], effects: [] },
    { id: "match", label: "Valider les paires", kind: "match", actor: "active_player", oncePerPhase: true, itemIds: ["cat", "dog", "red", "blue"], effects: [] },
    { id: "play_card", label: "Jouer la carte", kind: "play_card", actor: "active_player", oncePerPhase: true, deckId: "tools", effects: [{ kind: "discard_selected_card", deckId: "tools", target: "actor" }] },
    { id: "choose", label: "Valider le choix", kind: "choose", actor: "active_player", oncePerPhase: true, optionIds: ["answer_a", "answer_b"], effects: [{ kind: "reveal", revealId: "clue_one" }] },
    { id: "write", label: "Envoyer la réponse", kind: "text", actor: "active_player", oncePerPhase: true, effects: [{ kind: "reveal", revealId: "secret_panel" }] },
    { id: "draw", label: "Piocher un outil", kind: "draw", actor: "active_player", oncePerPhase: true, deckId: "tools", effects: [{ kind: "draw_cards", deckId: "tools", count: 1, target: "actor" }] },
    { id: "complete", label: "Défi accompli", kind: "complete_challenge", actor: "active_player", oncePerPhase: true, effects: [{ kind: "add_score", target: "actor", amount: 1 }] },
    { id: "finish", label: "Terminer la fixture", kind: "advance", actor: "active_player", oncePerPhase: true, effects: [{ kind: "end_game", winnerBy: "highest_score" }] },
  ],
  rules: [{ id: "reward_order", trigger: { kind: "after_action", actionId: "order" }, conditionMode: "all", conditions: [{ kind: "last_input_correct", actionId: "order" }], effects: [{ kind: "add_score", target: "actor", amount: 3 }] }],
  phases: [{ id: "play", title: "Banc d’essai", componentIds: ["header", "prompt", "players", "choices", "text", "drawing", "clues", "challenge", "reveal", "board", "deck", "hand", "resources", "die", "spinner", "buzz", "order", "match", "media", "outcome"], actionIds: ["move", "energize", "roll", "spin", "buzz", "order", "match", "play_card", "choose", "write", "draw", "complete", "finish"], completionMode: "manual", completionConditions: [], onComplete: [] }],
};

for (const fixture of [cinemaCharadesSpec, systemsLabSpec]) {
  const validation = validateComposedGameSpec(fixture);
  if (!validation.ok) {
    throw new Error(`Invalid composed fixture ${fixture.id}: ${JSON.stringify(validation.issues)}`);
  }
}
